//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTemplates.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Impact_1200_Latin1Entities : DbContext
    {
        public Impact_1200_Latin1Entities()
            : base("name=Impact_1200_Latin1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IMP_CALENDAR> IMP_CALENDAR { get; set; }
        public DbSet<IMP_CALENDAR_INVALID_DAYS> IMP_CALENDAR_INVALID_DAYS { get; set; }
        public DbSet<IMP_CALENDAR_WORKDAY> IMP_CALENDAR_WORKDAY { get; set; }
    }
}
