//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_CALENDAR_INVALID_DAYS
    {
        public string FACTORY { get; set; }
        public string PROJECT { get; set; }
        public string CALENDAR { get; set; }
        public System.DateTime DAY { get; set; }
        public int DAY_TYPE { get; set; }
        public string CHANGED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    }
}
